HTML_SENSOR_NAMES = dict(
    pm_2_5="PM<sub>2.5</sub>",
    pm_2_5_prediction="PM<sub>2.5</sub> (Prediction)",
    pm_0_1="PM<sub>0.1</sub> (linear regression)",
    pm_0_1_forecast="PM<sub>0.1</sub> (ANN)",
    pm_1="PM<sub>1</sub> (linear regression)",
    pm_10="PM<sub>10</sub>",
    pm_100="PM<sub>100</sub>",
    wind_speed="Wind Speed",
    wind_direction="Wind Direction",
    temperature="Temperture",
    humidity="Humidity",
    voc="VOC",
    co="CO",
    co2="CO<sub>2</sub>",
    so2="SO<sub>2</sub>",
    o3="O<sub>3</sub>",
    no2="NO<sub>2</sub>",
    rain="Rain",
    pressure="Pressure",
    dew_point="Dew Point",
    visible="Visible",
)

HTML_SENSOR_UNITS = dict(
    pm_0_1="μg/m<sup>3</sup>",
    pm_0_1_forecast="μg/m<sup>3</sup>",
    pm_2_5="μg/m<sup>3</sup>",
    pm_2_5_prediction="μg/m<sup>3</sup>",
    pm_100="μg/m<sup>3</sup>",
    pm_10="μg/m<sup>3</sup>",
    pm_1_0="μg/m<sup>3</sup>",
    pm_1="μg/m<sup>3</sup>",
    wind_speed="knots",
    humidity="%",
    wind_direction="&deg;",
    temperature="&deg;C",
    dew_point="&deg;C",
    visible="km",
    pressure="mmHg",
    rain="mm",
    voc="ppb",
    co="ppm",
    co2="ppm",
    so2="ppb",
    o3="ppb",
    no2="ppb",
)

HTML_CLIMATE_LEGENDS = dict(
    air4thai=[
        {"DES": "ดีมาก 0-15mg/m<sup>3</sup>", "fill": "#00BFFF"},
        {"DES": "ดี 15-25mg/m<sup>3</sup>", "fill": "#01DF3A"},
        {"DES": "ปานกลาง 25-37.5mg/m<sup>3</sup>", "fill": "#FFE319"},
        {"DES": "เริ่มมีผลกระทบต่อสุขภาพ 37.5-75mg/m<sup>3</sup>", "fill": "#FF8000"},
        {"DES": "มีผลกระทบต่อสุขภาพ >75mg/m<sup>3</sup>", "fill": "#FF0000"},
    ],
    santhings=[
        {"DES": "ดีมาก 0-15mg/m<sup>3</sup>", "fill": "#00BFFF"},
        {"DES": "ดี 15-25mg/m<sup>3</sup>", "fill": "#01DF3A"},
        {"DES": "ปานกลาง 25-37.5mg/m<sup>3</sup>", "fill": "#FFE319"},
        {"DES": "เริ่มมีผลกระทบต่อสุขภาพ 37.5-75mg/m<sup>3</sup>", "fill": "#FF8000"},
        {"DES": "มีผลกระทบต่อสุขภาพ >75mg/m<sup>3</sup>", "fill": "#FF0000"},
    ],
    airport=[
        {"DES": "calm", "fill": "#026701"},
        {"DES": "very light", "fill": "#099900"},
        {"DES": "gentle breeze", "fill": "#CEFF68"},
        {"DES": "moderate breeze", "fill": "#FEFF99"},
        {"DES": "fresh breeze", "fill": "#FFFF67"},
        {"DES": "strong breeze", "fill": "#FFFF01"},
        {"DES": "near gale", "fill": "#FFCB00"},
        {"DES": "gale", "fill": "#FF9900"},
        {"DES": "strong gale", "fill": "#FF3300"},
        {"DES": "storm", "fill": "#CD0001"},
        {"DES": "violent storm", "fill": "#A50022"},
        {"DES": "hurricane", "fill": "#670032"},
    ],
    PM_0_1=[
        {"DES": "ดีมาก 0-2.25µg/m<sup>3</sup>", "fill": "#00BFFF"},
        {"DES": "ดี 2.26-3.75µg/m<sup>3</sup>", "fill": "#01DF3A"},
        {"DES": "ปานกลาง 3.76-5.63µg/m<sup>3</sup>", "fill": "#FFE319"},
        {
            "DES": "เริ่มมีผลกระทบต่อสุขภาพ 5.64-11.25µg/m<sup>3</sup>",
            "fill": "#FF8000",
        },
        {"DES": "มีผลกระทบต่อสุขภาพ >11.26µg/m<sup>3</sup>", "fill": "#FF0000"},
    ],
    PM_0_1_forecast=[
        {"DES": "ดีมาก 0-2.25µg/m<sup>3</sup>", "fill": "#00BFFF"},
        {"DES": "ดี 2.26-3.75µg/m<sup>3</sup>", "fill": "#01DF3A"},
        {"DES": "สีเหลือง 3.76-5.63µg/m<sup>3</sup>", "fill": "#FFE319"},
        {
            "DES": "สีส้ม 5.64-11.25µg/m<sup>3</sup>",
            "fill": "#FF8000",
        },
        {"DES": "สีแดง >11.26µg/m<sup>3</sup>", "fill": "#FF0000"},
    ],
    PM_1=[
        {"DES": "ดีมาก 0-2.25µg/m<sup>3</sup>", "fill": "#00BFFF"},
        {"DES": "ดี 2.26-3.75µg/m<sup>3</sup>", "fill": "#01DF3A"},
        {"DES": "สีเหลือง 3.76-5.63µg/m<sup>3</sup>", "fill": "#FFE319"},
        {
            "DES": "สีส้ม 5.64-11.25µg/m<sup>3</sup>",
            "fill": "#FF8000",
        },
        {"DES": "สีแดง >11.26µg/m<sup>3</sup>", "fill": "#FF0000"},
    ],
    PM_2_5=[
        {"DES": "ดีมาก 0-15mg/m<sup>3</sup>", "fill": "#00BFFF"},
        {"DES": "ดี 15-25mg/m<sup>3</sup>", "fill": "#01DF3A"},
        {"DES": "ปานกลาง 25-37.5mg/m<sup>3</sup>", "fill": "#FFE319"},
        {"DES": "เริ่มมีผลกระทบต่อสุขภาพ 37.5-75mg/m<sup>3</sup>", "fill": "#FF8000"},
        {"DES": "มีผลกระทบต่อสุขภาพ >75mg/m<sup>3</sup>", "fill": "#FF0000"},
    ],
    PM_2_5_prediction=[
        {"DES": "ดีมาก 0-15mg/m<sup>3</sup>", "fill": "#00BFFF"},
        {"DES": "ดี 15-25mg/m<sup>3</sup>", "fill": "#01DF3A"},
        {"DES": "ปานกลาง 25-37.5mg/m<sup>3</sup>", "fill": "#FFE319"},
        {"DES": "เริ่มมีผลกระทบต่อสุขภาพ 37.5-75mg/m<sup>3</sup>", "fill": "#FF8000"},
        {"DES": "มีผลกระทบต่อสุขภาพ >75mg/m<sup>3</sup>", "fill": "#FF0000"},
    ],
    wind_direction=[
        {"DES": "calm", "fill": "#026701"},
        {"DES": "very light", "fill": "#099900"},
        {"DES": "gentle breeze", "fill": "#CEFF68"},
        {"DES": "moderate breeze", "fill": "#FEFF99"},
        {"DES": "fresh breeze", "fill": "#FFFF67"},
        {"DES": "strong breeze", "fill": "#FFFF01"},
        {"DES": "near gale", "fill": "#FFCB00"},
        {"DES": "gale", "fill": "#FF9900"},
        {"DES": "strong gale", "fill": "#FF3300"},
        {"DES": "storm", "fill": "#CD0001"},
        {"DES": "violent storm", "fill": "#A50022"},
        {"DES": "hurricane", "fill": "#670032"},
    ],
    PM_10=[
        {"DES": "ดีมาก 0-50mg/m<sup>3</sup>", "fill": "#00BFFF"},
        {"DES": "ดี 50-80mg/m<sup>3</sup>", "fill": "#01DF3A"},
        {"DES": "ปานกลาง 80-120mg/m<sup>3</sup>", "fill": "#FFE319"},
        {"DES": "เริ่มมีผลกระทบต่อสุขภาพ 120-180mg/m<sup>3</sup>", "fill": "#FF8000"},
        {"DES": "มีผลกระทบต่อสุขภาพ >180mg/m<sup>3</sup>", "fill": "#FF0000"},
    ],
    temperature=[
        {"DES": "0-15<sup>°</sup>C", "fill": "#FE2EF7"},
        {"DES": "15-20<sup>°</sup>C", "fill": "#8904B1"},
        {"DES": "20-25<sup>°</sup>C", "fill": "#0040FF"},
        {"DES": "25-30<sup>°</sup>C", "fill": "#00BFFF"},
        {"DES": "30-35<sup>°</sup>C", "fill": "#FFE319"},
        {"DES": "35-40<sup>°</sup>C", "fill": "#FF8000"},
        {"DES": ">40<sup>°</sup>C", "fill": "#FF0000"},
    ],
    humidity=[
        {"DES": "0-30 %RH", "fill": "#FE2EF7"},
        {"DES": "30-60 %RH", "fill": "#53B06E"},
        {"DES": "60-90 %RH", "fill": "#1CD2C7"},
        {"DES": ">90 %RH", "fill": "#000080"},
    ],
    rain=[
        {"DES": "0-10 mm (Light Rain)", "level": "Light", "fill": "#cce5ff"},
        {"DES": "10-30 mm (Moderate Rain)", "level": "Moderate", "fill": "#66b2ff"},
        {"DES": "30-50 mm (Heavy Rain)", "level": "Heavy", "fill": "#0073e6"},
        {
            "DES": "50-100 mm (Very Heavy Rain)",
            "level": "Very Heavy",
            "fill": "#004080",
        },
        {"DES": ">100 mm (Extreme Rain)", "level": "Extreme", "fill": "#800080"},
    ],
    pressure=[
        {"DES": "<730 mmHg (Very Low)", "level": "Very Low", "fill": "#0000ff"},
        {"DES": "730-740 mmHg (Low)", "level": "Low", "fill": "#66b2ff"},
        {"DES": "740-750 mmHg (Normal)", "level": "Normal", "fill": "#ffffff"},
        {"DES": "750-760 mmHg (High)", "level": "High", "fill": "#ff9999"},
        {"DES": ">760 mmHg (Very High)", "level": "Very High", "fill": "#ff0000"},
    ],
    CO=[
        {"DES": "0-4.4 ppm (Good)", "level": "Good", "fill": "#00e400"},
        {"DES": "4.5-9.4 ppm (Moderate)", "level": "Moderate", "fill": "#ffff00"},
        {
            "DES": "9.5-12.4 ppm (Unhealthy for Sensitive Groups)",
            "level": "USG",
            "fill": "#ff7e00",
        },
        {"DES": "12.5-15.4 ppm (Unhealthy)", "level": "Unhealthy", "fill": "#ff0000"},
        {
            "DES": ">15.5 ppm (Very Unhealthy)",
            "level": "Very Unhealthy",
            "fill": "#7e0023",
        },
    ],
    O3=[
        {"DES": "0-50 ppb (Good)", "level": "Good", "fill": "#00e400"},
        {"DES": "51-100 ppb (Moderate)", "level": "Moderate", "fill": "#ffff00"},
        {
            "DES": "101-150 ppb (Unhealthy for Sensitive Groups)",
            "level": "USG",
            "fill": "#ff7e00",
        },
        {"DES": ">150 ppb (Unhealthy)", "level": "Unhealthy", "fill": "#ff0000"},
    ],
    SO2=[
        {"DES": "0-35 ppb (Good)", "level": "Good", "fill": "#00e400"},
        {"DES": "36-75 ppb (Moderate)", "level": "Moderate", "fill": "#ffff00"},
        {
            "DES": "76-185 ppb (Unhealthy for Sensitive Groups)",
            "level": "USG",
            "fill": "#ff7e00",
        },
        {"DES": ">185 ppb (Unhealthy)", "level": "Unhealthy", "fill": "#ff0000"},
    ],
    NO2=[
        {"DES": "0-53 ppb (Good)", "level": "Good", "fill": "#00e400"},
        {"DES": "54-100 ppb (Moderate)", "level": "Moderate", "fill": "#ffff00"},
        {
            "DES": "101-360 ppb (Unhealthy for Sensitive Groups)",
            "level": "USG",
            "fill": "#ff7e00",
        },
        {"DES": "361-649 ppb (Unhealthy)", "level": "Unhealthy", "fill": "#ff0000"},
        {
            "DES": ">650 ppb (Very Unhealthy)",
            "level": "Very Unhealthy",
            "fill": "#8f3f97",
        },
    ],
    AOD=[
        {"DES": "ดีมาก 0-15mg/m<sup>3</sup>", "fill": "#00BFFF"},
        {"DES": "ดี 15-25mg/m<sup>3</sup>", "fill": "#01DF3A"},
        {"DES": "ปานกลาง 25-37.5mg/m<sup>3</sup>", "fill": "#FFE319"},
        {"DES": "เริ่มมีผลกระทบต่อสุขภาพ 37.5-75mg/m<sup>3</sup>", "fill": "#FF8000"},
        {"DES": "มีผลกระทบต่อสุขภาพ >75mg/m<sup>3</sup>", "fill": "#FF0000"},
    ],
)


HTML_CLIMATE_LEGEND_TITLES = dict(
    air4thai="PCD ความเข้มข้นของ PM<sub>2.5</sub> (หมายเหตุ สีอ้างอิงจากกรมมลพิษ)",
    santhings="Airthai ความเข้มข้นของ PM<sub>2.5</sub> (หมายเหตุ สีอ้างอิงจากกรมมลพิษ)",
    airport="Airport Wind Speed & Direction",
    PM_0_1="ความเข้มข้นของ PM<sub>0.1</sub> (หมายเหตุ 15% ของ PM2.5 แสดงถึงความสูงต่ำไม่เกี่ยวกับสุขภาพ (อยู่ระหว่างการวิจัย))",
    PM_0_1_forecast="ความเข้มข้นของ PM<sub>0.1</sub> (ANN) (หมายเหตุ 15% ของ PM2.5 แสดงถึงความสูงต่ำไม่เกี่ยวกับสุขภาพ (อยู่ระหว่างการวิจัย))",
    PM_1="ความเข้มข้นของ PM<sub>1</sub> (หมายเหตุ 80% ของ PM2.5 แสดงถึงความสูงต่ำไม่เกี่ยวกับสุขภาพ (อยู่ระหว่างการวิจัย))",
    PM_2_5="ความเข้มข้นของ PM<sub>2.5</sub> (หมายเหตุ สีอ้างอิงจากกรมมลพิษ)",
    PM_2_5_prediction="ความเข้มข้นของ PM<sub>2.5</sub> (การพยากรณ์ล่วงหน้า) (หมายเหตุ สีอ้างอิงจากกรมมลพิษ)",
    wind_direction="Wind Speed",
    PM_10="ความเข้มข้นของ PM<sub>10</sub> (หมายเหตุ สีอ้างอิงจากกรมมลพิษ)",
    temperature="Temperature",
    humidity="Humidity",
    AOD="ความเข้มข้นของ PM<sub>2.5</sub> (หมายเหตุ สีอ้างอิงจากกรมมลพิษ)",
    rain="Rainfall (mm)",
    pressure="Pressure (mmHg)",
    CO="CO Concentration (ppm)",
    O3="Ozone Concentration (ppb)",
    SO2="SO<sub>2</sub> Concentration (ppb)",
    NO2="NO<sub>2</sub> Concentration (ppb)",
)

INTERPOLATION_SENSOR_TYPES_WITH_LEGEND = dict(
    PM_2_5={
        "get_colors_config": lambda upper_bound: [
            (0, "#00BFFF"),
            (15, "#01DF3A"),
            (25, "#FFE319"),
            (37.5, "#FF8000"),
            (75, "#FF0000"),
            (upper_bound, "#FF0000"),
        ]
    }
)
